version: "3.7"
services:
  nginx:
    image: nginx
    container_name: ${DOCKER_PREFIX}nginx
    working_dir: ${DOCKER_SOURCE_DIR}
    volumes:
      - .:${DOCKER_SOURCE_DIR}
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "${DOCKER_HTTP_PORT}:80"
    networks:
      - net
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${DOCKER_PREFIX}php
    environment:
      XDEBUG_CONFIG: "
        remote_host=${DOCKER_HOST_IP}
        idekey=PHPSTORM
        remote_enable=1
        remote_autostart=0
        remote_connect_back=0
        remote_port=9000
        scream=0
        show_local_vars=1"
      PHP_IDE_CONFIG: serverName=docker
    working_dir: ${DOCKER_SOURCE_DIR}
    volumes:
      - ./:${DOCKER_SOURCE_DIR}
    networks:
      - net
    depends_on:
      - mongo
      - postgres

  postgres:
    image: postgres:11
    container_name: ${DOCKER_PREFIX}postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "${DOCKER_POSTGRES_PORT}:5432"
    networks:
      - net

  mongo:
    image: mongo
    container_name: ${DOCKER_PREFIX}mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${DOCKER_MONGO_PORT}:27017"
    networks:
      - net

networks:
  net:
    name: ${DOCKER_PREFIX}network
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}

volumes:
  data: {}